### PR TITLE
Devkit

### PR DESCRIPTION
**Pull request by Thekit789**
merge feature serviceslist to developfrontend

### CODE REVIEW

**Comment by earthfm1670** [comment]
approved merge

**Review by Wannasingh — APPROVED** [review]
look good to me.

**Review by earthfm1670 — APPROVED** [review]

**Review by Thanapat1502 — APPROVED** [review]
Fix and approved.

**Review by PotterWinter — APPROVED** [review]
approve this change is for fix github to revert at some point by all team

**Pull request merged**
