### PR TITLE
Feature/navbar

### PR DESCRIPTION
**Pull request by earthfm1670**
Update navbar to take login/logout useState
Add shadcn dropdown to the user profile in navbar once logged in
Dropdown consist of dashboard rediction and logout button
Add handle logout button to clear token
Navbar will render user data accordingly to the user

### CODE REVIEW

**Review by PotterWinter — APPROVED** [review]
approve by korn

**Review by Wannasingh — APPROVED** [review]
approved.

**Review by Thanapat1502 — APPROVED** [review]
Review and approved

**Review by Thekit789 — APPROVED** [review]
Approve

Update navbar to take login/logout useState

**Pull request merged**
